
name: Flask CI/CD Pipeline

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m pytest flask_app/tests.py -v

  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.STAGING_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Deploy to Staging
      env:
        HOST: ${{ secrets.STAGING_HOST }}
        USER: ${{ secrets.STAGING_USER }}
      run: |
        echo "Deploying to staging server at ${HOST}"
        ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "
          cd /home/ubuntu/flask-app && \
          git fetch origin staging && \
          git reset --hard origin/staging && \
          pip install -r requirements.txt && \
          sudo systemctl restart flask-app
        "
